using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class EnemyBase : MonoBehaviour
{
    public float enemyBaseHealth = 500; // 콯ivoty z치kladny
    public Slider healthSlider;


    public GameObject enemyWarrPrefab;  // Prefab pro b캩쬹칠ho nep콏칤tele (Warrior)
    public GameObject enemyArcherPrefab; // Prefab pro Archera

    public GameObject winScreen;

    public Transform spawnPosArcher;
    public Transform spawnPosWarrior;
    private float spawnInterval;

    private float targetTime;

    // Start is called before the first frame update
    void Start()
    {
        
        targetTime = 3;

        if (healthSlider != null)
        {
            healthSlider.maxValue = enemyBaseHealth;
            healthSlider.value = enemyBaseHealth;
        }
    }
    private void Update()
    {
        targetTime -= Time.deltaTime;
        if (targetTime <= 0)
        {
            SpawnEnemy();
            targetTime = Random.Range(5, 15);
            
        }
        //Debug.Log(targetTime);

    }

    

    public void TakeDamage(float damage)
    {
        enemyBaseHealth -= damage;
        Debug.Log("Nep콏치telsk치 z치kladna dostala damage: " + damage + ". Zb칳vaj칤c칤 HP: " + enemyBaseHealth);

        if (healthSlider != null)
        {
            healthSlider.value = enemyBaseHealth;
        }

        if (enemyBaseHealth <= 0)
        {
            DestroyBase();
        }
    }

    void DestroyBase()
    {
        Debug.Log("Nep콏치telsk치 z치kladna byla zni캜ena!");
        Destroy(gameObject); // Zni캜칤 z치kladnu
        winScreen.gameObject.SetActive(true);
        Time.timeScale = 0f;//Zasdtav칤 캜as
    }

    private void SpawnEnemy()
    {
        GameObject enemyToSpawn;
        Transform spawnPos;

        // 1/3 코ance na spawn Archera, jinak se spawne Warrior
        if (Random.value < 0.33f)
        {
            enemyToSpawn = enemyArcherPrefab;
            spawnPos = spawnPosArcher;
            Debug.Log("游릭 Spawnov치n EnemyArcher!");
        }
        else
        {
            spawnPos = spawnPosWarrior;
            enemyToSpawn = enemyWarrPrefab;
            Debug.Log("游댮 Spawnov치n EnemyWarrior!");
        }

        Instantiate(enemyToSpawn, spawnPos.position, Quaternion.identity);
    }
}
